### PR TITLE
Fix #320: Use flatten, copy and counts

### LINKED ISSUE #320: FactorizedJetCorrector incorrectly handles JaggedArrays
**Describe the bug**
The `getSubCorrections` and subsequently the `getCorrection` methods of `FactorizedJetCorrector` incorrectly handle JaggedAttays. It modifies the content of the inputs and raises an error when using a starts-stops JaggedArray.

**To Reproduce**
```
import awkward
import coffea
extract = coffea.lookup_tools.extractor()
extract.add_weight_sets(['* * tests/samples/Summer16_23Sep2016V3_MC_L2Relative_AK4PFPuppi.jec.txt.gz'])
extract.finalize()
evaluator = extract.make_evaluator()
corrector = coffea.jetmet_tools.FactorizedJetCorrector(**evaluator)
eta = awkward.JaggedArray.fromcounts([1, 1], [0., 0.])
rho = awkward.JaggedArray.fromcounts([1, 1], [30., 30.])
pt = awkward.JaggedArray.fromcounts([1, 1], [100., 100.])
area = awkward.JaggedArray.fromcounts([1, 1], [0.5, 0.5])
corrector.getCorrection(JetPt=pt, JetEta=eta, JetA=area, Rho=rho)
print(pt)
```
`pt` will surprisingly be changed by the `getCorrection` call and will be around 109 now.
On top of that with a starts-stops JaggedArray:
```
pt = awkward.JaggedArray([2, 3], [3, 4], [float("nan"), float("nan"), 100., 100.])
corrector.getCorrection(JetPt=pt, JetEta=eta, JetA=area, Rho=rho)
```
one will get a `ValueError`.

### PR DESCRIPTION
**Pull request by jrueb**
This fixes #320 and also adds a test case for the bug.

### CODE REVIEW

**Comment by lgray** [comment]
Thanks!

My one comment is why you need to use counts rather than offsets?

**Comment by jrueb** [comment]
You will get a value error for trying to get the offsets of something like `awkward.JaggedArray([0, 2], [1, 3], [7, 8, 9])`.
In the case of `FactorizedJetCorrector` this would happen if the eta is such a jagged array that is defined by starts and stops with gaps in-between.

**Comment by lgray** [comment]
Ah right, this was only working on compact arrays. 
You could use starts and stops directly, but I think the performance difference for this function is minimal. 

Otherwise looks good. Thanks!

**Comment by lgray** [comment]
Do you need a release cut for this now or can we wait for a few more items to come in?

**Comment by jrueb** [comment]
If you want, you can wait. I don't mind.

**Pull request merged**
