### PR TITLE
Add a stub to make histograms compatible with striped client

### PR DESCRIPTION
**Pull request by nsmith-**
A server side change is also necessary.
For people using the docker micro server container, here's a patch:
https://gist.github.com/nsmith-/db35bca2994ba39f6286b56ff616d858

### CODE REVIEW

**Comment by nsmith-** [comment]
What the heck, I didn't even touch that file and can't reproduce build failure locally.

**Comment by lgray** [comment]
Nope

**Comment by lgray** [comment]
This problem is caused by the issue reported here in uproot: 
https://github.com/scikit-hep/uproot-methods/issues/31

@jpivarski

**Comment by nsmith-** [comment]
Will tackle the uproot-methods change separately.

**Pull request merged**
