### PR TITLE
Fix crash in iterative executor from workers

### PR DESCRIPTION
**Pull request by lgray**
Addresses #96.

- have separate "pre_workers" for preprocessing
- add tests

@nsmith-

### CODE REVIEW

**Comment by nsmith-** [comment]
There must be a better pattern than using `**kwargs` as a gutter for extra params, but otherwise OK.

**Comment by nsmith-** [comment]
Also can we make codecov shut up?

**Comment by lgray** [comment]
Yeah I'll get it to be quiet.

**Comment by lgray** [comment]
@aminnj This will be fixed in v0.5.1, or already in master.

**Pull request merged**
