### PR TITLE
work queue executor refactor

### PR DESCRIPTION
**Pull request by btovar**
A much needed refactor of the wq code. It changes some things to match the rest of coffea, such as:

- change from tqdm to rich_bar
- change from dill to cloud_pickle
- on error, accumulate as much as possible so that run can be restarted (e.g. with wrapped_out["unprocessed'])
- update documentation to show use of ssl and passwords.
- reduce parameter clutter using executor object
- update chunksize on chunk split with memory exhaustion
- deprecated chunks_in_mem_accum  (always 2)
- deprecated chunks_per_accum, renamed to treereduction
- deprecated master_name, renamed to manager_name

Most of it was moving the executor functions to methods of class representing the queue.

### CODE REVIEW

**Comment by btovar** [comment]
This one should be ready to merge.

**Comment by lgray** [comment]
Sorry for lagging on this one - all good to go @btovar ?

**Comment by btovar** [comment]
All good!

**Comment by btovar** [comment]
@lgray thanks!

**Pull request merged**
