### PR TITLE
feat: Add bokeh proj

### PR DESCRIPTION
**Pull request by andrzejnovak**
Probably doesn't make sense to add bokeh as a requirement just yet.

### CODE REVIEW

**Comment by lgray** [comment]
Address the linter and we're good to go:
```
coffea/hist/plot.py:667:57: E272 multiple spaces before keyword
coffea/hist/plot.py:675:1: W293 blank line contains whitespace
coffea/hist/plot.py:680:18: F821 undefined name 'palettes'
coffea/hist/plot.py:687:5: E303 too many blank lines (2)
coffea/hist/plot.py:693:1: W293 blank line contains whitespace
coffea/hist/plot.py:697:1: W293 blank line contains whitespace
coffea/hist/plot.py:704:1: W293 blank line contains whitespace
coffea/hist/plot.py:707:1: W293 blank line contains whitespace
coffea/hist/plot.py:730:1: W293 blank line contains whitespace
coffea/hist/plot.py:749:43: W291 trailing whitespace
coffea/hist/plot.py:751:30: E261 at least two spaces before inline comment
coffea/hist/plot.py:751:30: E262 inline comment should start with '# '
coffea/hist/plot.py:769:19: E231 missing whitespace after ','
coffea/hist/plot.py:769:22: E231 missing whitespace after ','
coffea/hist/plot.py:770:1: W391 blank line at end of file
coffea/hist/plot.py:770:1: W293 blank line contains whitespace
```

**Comment by andrzejnovak** [comment]
@lgray I'm gonna leave this hanging for a bit longer. There are a few things I'd like to improve.

**Comment by lgray** [comment]
@andrzejnovak ah ok, gotcha!

**Comment by andrzejnovak** [comment]
@lgray I'd say this is good to go. Try it out :)

**Comment by andrzejnovak** [comment]
@lgray umm?

**Pull request merged**
