### PR TITLE
feat: add low-pt electrons to NanoAOD methods and schema

### LINKED ISSUE #1120: LowPtElectron is missing in nanoaod methods and the schema
`LowPtElectron` class should be added  in the nanoevents methods and to the nanoaod schema.

### PR DESCRIPTION
**Pull request by ikrommyd**
Fixes https://github.com/CoffeaTeam/coffea/issues/1120

### CODE REVIEW

**Comment by lgray** [comment]
Can you post some proof that all of this works on modern nanoaod or otherwise add a concise test?

**Comment by ikrommyd** [comment]
Yeah I wanted to ask about this and that’s why I didn’t do it yet. Would you be okay with modifying the contents of nano_dy.root to add some mock low pt electrons, perhaps by just copying values from regular electrons?

**Comment by lgray** [comment]
I would skim a nanoaod to 40 events and have new file to test. I wouldn't update the old file because then you'll have to change all the tests to match the new events, which would be a pain.

**Comment by lgray** [comment]
I'd also be satisfied with an example from you running a notebook, or something similar, that demonstrates the new functionality works as expected.

**Comment by ikrommyd** [comment]
Are we happy with this?
```python
In [1]: from coffea.nanoevents import NanoEventsFactory
   ...:
   ...: events = NanoEventsFactory.from_root(
   ...:     {
   ...:         "root://eoscms.cern.ch:1094//eos/cms//store/mc/Run3Winter24NanoAOD/DYJetsToLL_M-50_TuneCP5_13p6TeV-madgraphMLM-pythia8/NANOAODSIM/NoPU_Pilot_133X_mcRun3_2024_realistic_v6-v2/50000/976308db-41c9-4b50-b297-d2577ef22e4b.root": "Events"
   ...:     }
   ...: ).events()
/Users/iason/work/coffea_dev/coffea/src/coffea/nanoevents/methods/candidate.py:11: FutureWarning: In version 2024.7.0 (target date: 2024-06-30 11:59:59-05:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  from coffea.nanoevents.methods import vector

In [2]: events.LowPtElectron.compute()
Out[2]: <LowPtElectronArray [[], [LowPtElectron, LowPtElectron], ..., [], []] type='...'>

In [3]: events.LowPtElectron.matched_gen.compute()
Out[3]: <GenParticleArray [[], [GenParticle, GenParticle], ..., [], []] type='1941 ...'>

In [4]: events.LowPtElectron.matched_electron.compute()
Out[4]: <ElectronArray [[], [Electron, Electron], ..., [], []] type='1941 * var * ?...'>

In [5]: events.LowPtElectron.matched_photon.compute()
Out[5]: <PhotonArray [[], [None, None], [None], ..., [], []] type='1941 * var * ?Ph...'>

In [6]: events.LowPtElectron.metric_table(events.Electron).compute()
Out[6]: <Array [[], [[2.77, 0], [...]], ..., [], []] type='1941 * var * var * float32'>
```

**Comment by ikrommyd** [comment]
@lgray perhaps this can go in in order to make the necessary changes to https://github.com/CoffeaTeam/coffea/pull/991 as well before merging it?

**Pull request merged**
