### PR TITLE
Fix Cornercases: Empty formula and multiple formulas for btag SF

### PR DESCRIPTION
**Pull request by pfackeldey**
Dear coffea developers,

this PR implements fixes for two corner cases:

1. set the default scale factor formula to "1." in case the `this_bin` mask is empty
2. raise an Exception in case multiple formulas are found for the same bin

Thanks a lot in advance for reviewing!

PS:
I stumbled over the first corner case with the current deep flavour btag csv file in CMS (2017), where i just got an index out of bound error, since the `this_bin` mask was an empty array.

### CODE REVIEW

**Comment by nsmith-** [comment]
Hi, thanks for solving the parsing error!
You might be interested in looking at the revised b-tagging class implemented in #267 and documented in https://coffeateam.github.io/coffea/api/coffea.btag_tools.BTagScaleFactor.html#coffea.btag_tools.BTagScaleFactor

**Comment by pfackeldey** [comment]
Cool! Looks like I can also use this `BTagScaleFactor` class to extract the scale factors. Is this way recommended in comparison to using the `extractor` from `lookup_tools` ? 
(btw i fixed the flake8 linting)

**Comment by nsmith-** [comment]
You might find it easier to use, since it handles apply a SF to all flavors at once along the lines of the BTV class `eval_auto_bounds`

**Comment by pfackeldey** [comment]
Thanks a lot! I will try it out. :)

**Comment by lgray** [comment]
In the mean time, I'm going to merge this. Thanks a lot for the contribution!

Good to keep the older stuff running too, but I'll add a deprecation warning to the old btagging SF classes.

**Pull request merged**
