### PR TITLE
Fix bug in plot1d when overlay is None

### PR DESCRIPTION
**Pull request by nsmith-**
oops guess I stopped testing that one

### CODE REVIEW

**Comment by lgray** [comment]
Add a test :-)

**Comment by nsmith-** [comment]
how to test plots though

**Comment by lgray** [comment]
pickle.dumps should be constant over time? Use that to make comparison of plot objects?

**Comment by nsmith-** [comment]
https://matplotlib.org/devel/testing.html#writing-an-image-comparison-test
Later though

**Comment by lgray** [comment]
ah, cute

**Pull request merged**
