### PR TITLE
fix: Append originating filename to errors raised from proc

### PR DESCRIPTION
**Pull request by andrzejnovak**
Convenient for debugging. Appends filename to any error messaged raised from processor.

```

 When processing:
 /home/anovak/group/stocknano/17/store/mc/RunIIAutumn18NanoAODv7/QCD_HT50to100_TuneCP5_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/70000/04423DB6-79C3-9044-A847-D765F6ADDEA7.root

```

### CODE REVIEW

**Comment by nsmith-** [comment]
This is good, but I wonder if this can be added straight into uproot4 as an optional flag in the `open` call, some parameter like `add_context` that would modify the `ReadOnlyFile` context manager in https://github.com/scikit-hep/uproot4/blob/master/uproot4/reading.py#L649 to do something like the following example:

```python
def open_something(name):
    return name + "ctx"


def close_something(ctx):
    pass


class AddContext:
    def __init__(self, resource_name):
        self._name = resource_name

    def __enter__(self):
        self._ctx = open_something(self._name)
        return self._ctx

    def __exit__(self, exception_type, exception_value, traceback):
        if exception_value is not None:
            exception_value.args = (
                exception_value.args[0]
                + f"\n\nNote: raised in context AddContext({self._name})",
                *exception_value.args[1:],
            )
        close_something(self._ctx)


with AddContext("mything") as ctx:
    raise ValueError("Some problem")
```

which, when run, outputs:
```
$ python contextexc.py
Traceback (most recent call last):
  File "contextexc.py", line 24, in <module>
    raise ValueError("Some problem")
ValueError: Some problem

Note: raised in context AddContext(mything)
```

I stackoverflowed a bit and can't tell if modifying the exception in-place is a good strategy. Other options include using python3's `raise BlahException from original_exception` syntax.
@jpivarski thoughts on this?

**Comment by jpivarski** [comment]
In Uproot 4 (specifically 4), all of the objects that come out of a ROOT file have a context manager that propagates up a chain like

   * TBranch → TBranch → TTree → ReadOnlyDirectory → ReadOnlyFile → Source

to clean up everything that the Source made (open file handles and/or threads). That's so that you can

```python
with uproot4.open("file.root:/path/to/tree/branch/subbranch") as subbranch:
    subbranch.array()
```

and everything goes away after the one context manager exits. I don't want to encourage

```python
with uproot4.open("file.root") as directory:
    with directory["/path/to/tree/branch/subbranch"] as subbranch:
        subbranch.array()
    directory["/path/to/something/else"]?
```

because the inner context manager has already closed the file. But I don't think anybody wants to be writing nested context managers, anyway.

Introducing this `AddContext` gives us a reason to have nested context managers, and _if this is confused_, users could end up writing something like the above. This was a long-winded way of saying that I'd prefer the use of a context manager to be passed to the `uproot4.open` arguments (as one of the `options`, so that `uproot4.iterate`, `uproot4.concatenate`, and `uproot4.lazy` get it, too), so that your users don't get in the habit of writing nested `with` blocks and maybe thinking that it should be broken up at a fine-grained level, too.

Assuming we want this interface, there are two questions:

   1. When should the supplied `__exit__` be called? I assume it would be attached to the ReadOnlyFile. Is there a reason for it to be before or after the Source?
   2. Is there a reason to pass both `__enter__` and `__exit__`? The only reason I can see for `__enter__` is to change the object that gets returned `as` some variable, but if the function call is `uproot4.open`, the object that should be returned is ReadOnlyDirectory. If the interface is only `__exit__`, then it can just be a 3-argument function with ignored return value, and maybe the option name could be `atexit`, which is a familiar name for a similar function in Python.

But this feature that you just developed for Coffea, is it always used with Uproot? It looks like you'd want to use it with non-Uproot sources as well, in which case you'd want the separate context manager implementation, anyway.

Also, note that most of the failure modes in Uproot itself will tell you the file name. That was something someone requested a long time ago, was handled piecemeal in Uproot 3, and has been handled much more systematically in Uproot 4. That's why so many internal functions take a `file_path` argument (and sometimes also an `object_path`).

**Comment by nsmith-** [comment]
err, I was only demoing the fact that a context manager can add context to an exception. I don't mean for anyone to nest context managers, sorry if that was not clear.
> passed to the uproot4.open arguments (as one of the options, so that uproot4.iterate, uproot4.concatenate, and uproot4.lazy get it, too)

Indeed that's what I'm imagining, if a user writes:
```python
with uproot4.open("myfile.root", add_exception_context=True) as file:
    do_lots_of_things_that_may_error(file)
```
then, on _any_ exception, uproot will add the current filename to the message. The reason this goes beyond just uproot errors is often there are exceptions that are due to users not guarding against or otherwise not considering corner cases that depend on the data contents in the file. In coffea, when users might run the same code over thousands of files, if just one breaks their code it is very nice to know _which one_. This is exactly why Andrzej is trying to implement this feature.
I just pointed out that probably uproot could implement that by adding the lines in the demo into `ReadOnlyFile` or perhaps `Source`.

**Comment by jpivarski** [comment]
Oh, I thought idea #1 was to do

```python
with AddContext("mything") as ctx:
    with uproot4.open("flie.root") as file:
        ...
```

which _could lead_ people to start breaking things into even finer context managers, and that would lead to some errors.

Then I thought idea #2 was something like:

```python
with uproot4.open("file.root", atexit=addcontext) as file:
    ...
```

But really, you had something more in mind like

```python
with uproot4.open("file.root", add_filename_to_exception=True) as file:
    ...
```

Then, if the exception message doesn't already have an `in file [FILENAME]` line (i.e. not from Uproot or one of the corner cases where it didn't make sense), then Uproot would add one.

Since you're modifying the exception in-place, it won't show up as a chained exception, right? The most visible (last) stack trace will still point to the actual line of code where the exception happened?

About modifying that exception in-place, do they all have a mutable `args` attribute/property? I didn't know that was a rule that all derived exceptions must follow, and since it's user code in the block and users can make their own exceptions, would it work if a derived exception doesn't have this `args` interface? Or at least, if it doesn't print it out?

Although I don't like the monkey patching of this, it might be needed for full generality:

```python
def __exit__(self, exception_type, exception_value, traceback):
    if exception_value is not None:
        extra = "\nin file: " + self.file_path
        if extra not in str(exception_value):
            message = str(exception_value) + extra
            exception_value.__str__ = lambda self: message
```

but even that introduces a subtlety. If the user-defined exception was supposed to do something at the time that it is printed out (because some state changes, or maybe just to print an accurate time), then this prematurely evaluates it.

**Comment by nsmith-** [comment]
> Since you're modifying the exception in-place, it won't show up as a chained exception, right? The most visible (last) stack trace will still point to the actual line of code where the exception happened?

Yes, e.g. if I take the class from above and chain an exception:
```python
with AddContext("mything") as ctx:
    try:
        raise ValueError("Some problem")
    except ValueError:
        raise RuntimeError("Some other problem")
```
then the addition is still at the very end, which is a desirable property:
```
$ python contextexc.py
Traceback (most recent call last):
  File "contextexc.py", line 29, in <module>
    raise ValueError("Some problem")
ValueError: Some problem

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "contextexc.py", line 31, in <module>
    raise RuntimeError("Some other problem")
RuntimeError: Some other problem

Note: raised in context AddContext(mything)
```

If we instead re-raise:
```python
    def __exit__(self, exception_type, exception_value, traceback):
        close_something(self._ctx)
        raise Exception(f"Error encountered in processing {self._name}")
```
we get something like:
```
$ python contextexc.py
Traceback (most recent call last):
  File "contextexc.py", line 24, in <module>
    raise ValueError("Some problem")
ValueError: Some problem

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "contextexc.py", line 26, in <module>
    raise RuntimeError("Some other problem")
RuntimeError: Some other problem

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "contextexc.py", line 26, in <module>
    raise RuntimeError("Some other problem")
  File "contextexc.py", line 19, in __exit__
    raise Exception(f"Error encountered in processing {self._name}")
Exception: Error encountered in processing mything
```
which makes it harder for a downstream code to catch and understand the original exception and hides it one level up in the chain.

> About modifying that exception in-place, do they all have a mutable args attribute/property?

I am not sure. More generally, someone might even make a exception class where the first argument does something completely different than hold a string, in which case we cannot even be sure to properly edit it (as I was proposing) _or_ re-raise a modified copy of it (as @andrzejnovak did in this PR). Your solution solves the display issue, assuming no downstream library mangles it further (and might even make the very assumption you are guarding against) In that sense, the chained exception solution is the only safe option, but it has some disadvantages as mentioned before.

**Comment by andrzejnovak** [comment]
I would say the discussion is a bit academic since making it part of uproot seems like it would take a good amount more of discussion and testing, while the current PR is easy, working QoL improvement, that's available now.

**Comment by nsmith-** [comment]
Fair, I guess this implies coffea has lower standards. (probably true)
Can you check one more thing before we merge? Do chained exceptions get propagated correctly still using `with_traceback` as you have done?

**Comment by andrzejnovak** [comment]
Well, I'd say it's more about the fact the uproot is lower level and used by other libraries, which makes introducing stuff that's not easily testable more tricky? 

I am not 100%  sure what does chained exception being propagated mean, but here's an example with the change

<details>
  <summary>After</summary>

```
Traceback (most recent call last):
  File "/home/anovak/coffea/coffea/processor/executor.py", line 832, in _work_function
    out = processor_instance.process(events)
  File "/home/anovak/boostedhiggs/boostedhiggs/hbbprocessor.py", line 222, in process
    dphi = abs(jets.delta_phi(candidatejet))
  File "/home/anovak/coffea/coffea/nanoevents/methods/vector.py", line 144, in delta_phi
    return (self.phi - other.phi + numpy.pi) % (2 * numpy.pi) - numpy.pi
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/numpy/lib/mixins.py", line 21, in func
    return ufunc(self, other)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/highlevel.py", line 1380, in __array_ufunc__
    return awkward1._connect._numpy.array_ufunc(ufunc, method, inputs, kwargs)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_connect/_numpy.py", line 107, in array_ufunc
    out = awkward1._util.broadcast_and_apply(inputs, getfunction, behavior)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_util.py", line 972, in broadcast_and_apply
    out = apply(broadcast_pack(inputs, isscalar), 0)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_util.py", line 745, in apply
    outcontent = apply(nextinputs, depth + 1)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_util.py", line 695, in apply
    outcontent = apply(nextinputs, depth)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_util.py", line 824, in apply
    lencontent = nplike.max(stops)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/nplike.py", line 264, in max
    return self._module.max(*args, **kwargs)
  File "<__array_function__ internals>", line 6, in amax
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2706, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner.py", line 85, in <module>
    'workers': 4},
  File "/home/anovak/coffea/coffea/processor/executor.py", line 1126, in run_uproot_job
    executor(chunks, closure, wrapped_out, **exe_args)
  File "/home/anovak/coffea/coffea/processor/executor.py", line 505, in iterative_executor
    add_fn(accumulator, function(item))
  File "/home/anovak/coffea/coffea/processor/executor.py", line 129, in __call__
    out = self.function(*args, **kwargs)
  File "/home/anovak/coffea/coffea/processor/executor.py", line 875, in _work_function
    raise e
  File "/home/anovak/coffea/coffea/processor/executor.py", line 834, in _work_function
    raise type(e)(str(e) + '\n\n When processing: \n %s \n' % item.filename).with_traceback(sys.exc_info()[2])
  File "/home/anovak/coffea/coffea/processor/executor.py", line 832, in _work_function
    out = processor_instance.process(events)
  File "/home/anovak/boostedhiggs/boostedhiggs/hbbprocessor.py", line 222, in process
    dphi = abs(jets.delta_phi(candidatejet))
  File "/home/anovak/coffea/coffea/nanoevents/methods/vector.py", line 144, in delta_phi
    return (self.phi - other.phi + numpy.pi) % (2 * numpy.pi) - numpy.pi
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/numpy/lib/mixins.py", line 21, in func
    return ufunc(self, other)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/highlevel.py", line 1380, in __array_ufunc__
    return awkward1._connect._numpy.array_ufunc(ufunc, method, inputs, kwargs)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_connect/_numpy.py", line 107, in array_ufunc
    out = awkward1._util.broadcast_and_apply(inputs, getfunction, behavior)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_util.py", line 972, in broadcast_and_apply
    out = apply(broadcast_pack(inputs, isscalar), 0)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_util.py", line 745, in apply
    outcontent = apply(nextinputs, depth + 1)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_util.py", line 695, in apply
    outcontent = apply(nextinputs, depth)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_util.py", line 824, in apply
    lencontent = nplike.max(stops)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/nplike.py", line 264, in max
    return self._module.max(*args, **kwargs)
  File "<__array_function__ internals>", line 6, in amax
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2706, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

 When processing:
 /home/anovak/group/stocknano/17/store/mc/RunIIAutumn18NanoAODv7/QCD_HT100to200_TuneCP5_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/270000/5AA7B919-E94B-8D4F-BAE9-3DA4F4158A78.root
```
</details>

and before

<details>
  <summary>Before</summary>
 

```
Traceback (most recent call last):
  File "runner.py", line 85, in <module>
    'workers': 4},
  File "/home/anovak/coffea/coffea/processor/executor.py", line 1123, in run_uproot_job
    executor(chunks, closure, wrapped_out, **exe_args)
  File "/home/anovak/coffea/coffea/processor/executor.py", line 505, in iterative_executor
    add_fn(accumulator, function(item))
  File "/home/anovak/coffea/coffea/processor/executor.py", line 129, in __call__
    out = self.function(*args, **kwargs)
  File "/home/anovak/coffea/coffea/processor/executor.py", line 872, in _work_function
    raise e
  File "/home/anovak/coffea/coffea/processor/executor.py", line 831, in _work_function
    out = processor_instance.process(events)
  File "/home/anovak/boostedhiggs/boostedhiggs/hbbprocessor.py", line 222, in process
    dphi = abs(jets.delta_phi(candidatejet))
  File "/home/anovak/coffea/coffea/nanoevents/methods/vector.py", line 144, in delta_phi
    return (self.phi - other.phi + numpy.pi) % (2 * numpy.pi) - numpy.pi
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/numpy/lib/mixins.py", line 21, in func
    return ufunc(self, other)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/highlevel.py", line 1380, in __array_ufunc__
    return awkward1._connect._numpy.array_ufunc(ufunc, method, inputs, kwargs)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_connect/_numpy.py", line 107, in array_ufunc
    out = awkward1._util.broadcast_and_apply(inputs, getfunction, behavior)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_util.py", line 972, in broadcast_and_apply
    out = apply(broadcast_pack(inputs, isscalar), 0)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_util.py", line 745, in apply
    outcontent = apply(nextinputs, depth + 1)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_util.py", line 695, in apply
    outcontent = apply(nextinputs, depth)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_util.py", line 824, in apply
    lencontent = nplike.max(stops)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/nplike.py", line 264, in max
    return self._module.max(*args, **kwargs)
  File "<__array_function__ internals>", line 6, in amax
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2706, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

</details>

It actually looks like having both `str(e)` and `with_traceback()` ends up duplicating a lot of the exception info

There's a bit less duplication with just `raise type(e)(str(e) + '\n\n When processing: \n %s \n' % item.filename)` but I am tbh not entirely sure how to get rid of it entirely.

<details>

```
Traceback (most recent call last):
  File "/home/anovak/coffea/coffea/processor/executor.py", line 832, in _work_function
    out = processor_instance.process(events)
  File "/home/anovak/boostedhiggs/boostedhiggs/hbbprocessor.py", line 222, in process
    dphi = abs(jets.delta_phi(candidatejet))
  File "/home/anovak/coffea/coffea/nanoevents/methods/vector.py", line 144, in delta_phi
    return (self.phi - other.phi + numpy.pi) % (2 * numpy.pi) - numpy.pi
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/numpy/lib/mixins.py", line 21, in func
    return ufunc(self, other)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/highlevel.py", line 1380, in __array_ufunc__
    return awkward1._connect._numpy.array_ufunc(ufunc, method, inputs, kwargs)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_connect/_numpy.py", line 107, in array_ufunc
    out = awkward1._util.broadcast_and_apply(inputs, getfunction, behavior)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_util.py", line 972, in broadcast_and_apply
    out = apply(broadcast_pack(inputs, isscalar), 0)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_util.py", line 745, in apply
    outcontent = apply(nextinputs, depth + 1)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_util.py", line 695, in apply
    outcontent = apply(nextinputs, depth)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/_util.py", line 824, in apply
    lencontent = nplike.max(stops)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/awkward1/nplike.py", line 264, in max
    return self._module.max(*args, **kwargs)
  File "<__array_function__ internals>", line 6, in amax
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2706, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/beegfs/desy/user/anovak/miniconda3/envs/coffea/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner.py", line 85, in <module>
    'workers': 4},
  File "/home/anovak/coffea/coffea/processor/executor.py", line 1126, in run_uproot_job
    executor(chunks, closure, wrapped_out, **exe_args)
  File "/home/anovak/coffea/coffea/processor/executor.py", line 505, in iterative_executor
    add_fn(accumulator, function(item))
  File "/home/anovak/coffea/coffea/processor/executor.py", line 129, in __call__
    out = self.function(*args, **kwargs)
  File "/home/anovak/coffea/coffea/processor/executor.py", line 875, in _work_function
    raise e
  File "/home/anovak/coffea/coffea/processor/executor.py", line 834, in _work_function
    raise type(e)(str(e) + '\n\n When processing: \n %s \n' % item.filename)#.with_traceback(sys.exc_info()[2])
ValueError: zero-size array to reduction operation maximum which has no identity

 When processing:
 /home/anovak/group/stocknano/17/store/mc/RunIIAutumn18NanoAODv7/QCD_HT100to200_TuneCP5_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/270000/5AA7B919-E94B-8D4F-BAE9-3DA4F4158A78.root

```
</details>

**Comment by nsmith-** [comment]
I think you can get rid of the double-traceback via 
```python
raise type(e)(str(e) + '\n\n When processing: \n %s \n' % item.filename).with_traceback(sys.exc_info()[2]) from None
```

**Pull request merged**
