### PR TITLE
docs: Create CITATION.cff

### LINKED ISSUE #760: Add CITATION.cff
Hi. Can you please add a CITATION.cff file with information on how you want Coffea cited? This would be quite useful for properly referencing and citing the code.

c.f. https://github.com/scikit-hep/vector/pull/243 for an example and links to other discussions on this topic.

### PR DESCRIPTION
**Pull request by nsmith-**
Fixes #760

For DOI I picked the last non-release candidate version.

Please feel free to comment here your yaml snip following the template
```yaml
- family-names: "Smith"
  given-names: "Nicholas"
  affiliation: "Fermilab"
  orcid: "https://orcid.org/0000-0002-0324-3054"
  email: "nick.smith@cern.ch"
```
and I'll add it @btovar @yimuchen @andrzejnovak @JayjeetAtGithub @pfackeldey @nikoladze @gordonwatts @dthain (and many more... this is just the top 10 not counting bots)

We should also list two proceedings somewhere (in the README? or as a `preferred-citation`?)
- N. Smith et al 2020 EPJ Web Conf. 245 06012
- L. Gray et al 2023 J. Phys.: Conf. Ser. 2438 012033

### CODE REVIEW

**Comment by andrzejnovak** [comment]
```
- family-names: "Novak"
  given-names: "Andrzej"
  affiliation: "RWTH Aachen"
  orcid: "https://orcid.org/0000-0002-0389-5896"
```

**Comment by pfackeldey** [comment]
```yaml
- family-names: "Fackeldey"
  given-names: "Peter"
  affiliation: "RWTH Aachen University"
  orcid: "https://orcid.org/0000-0003-4932-7162"
  email: "peter.fackeldey@rwth-aachen.de"
```

**Comment by lgray** [comment]
I think preferred citation makes sense for the proceedings we have running around.

**Comment by btovar** [comment]
```yaml
- family-names: "Tovar"
  given-names: "Benjamin"
  affiliation: "University of Notre Dame"
  orcid: "https://orcid.org/0000-0002-5294-2281"
  email: "btovar@nd.edu"
```

**Comment by yimuchen** [comment]
```yaml 
- family-names: "Chen"
  given-names: "Yi-Mu"
  affiliation: "University of Maryland, College Park"
  orcid: "https://orcid.org/0000-0002-5795-4783"
  email: "yi-mu.chen@cern.ch"
```

**Comment by gordonwatts** [comment]
```yaml
- family-names: "Watts"
  given-names: "Gordon"
  affiliation: "University of Washington"
  orcid: "https://orcid.org/0000-0002-0753-7308"
  email: "gwatts@uw.edu"
````

**Comment by lgray** [comment]
@iasonkrom would you like to be in the authors list? You've contributed a good chunk of stuff.

**Comment by ikrommyd** [comment]
> @iasonkrom would you like to be in the authors list? You've contributed a good chunk of stuff.

If y'all don't mind, sure!

**Comment by lgray** [comment]
@iasonkrom give me yaml

**Comment by ikrommyd** [comment]
```yaml
- family-names: "Krommydas"
  given-names: "Iason"
  affiliation: "Rice University"
  orcid: "https://orcid.org/0000-0001-7849-8863"
  email: "ik23@rice.edu"
```

**Comment by ikrommyd** [comment]
Thanks @lgray !!!

**Comment by lgray** [comment]
@jpata do you want to be on the authorlist here? You've haven't contributed for a while but everyone uses the lumitool and you definitely played into structure/ux/how things look today!

**Comment by lgray** [comment]
We can also just add more people later as they request.

**Comment by nsmith-** [comment]
Yeah I think we have a good start, can always add more later.

**Comment by nsmith-** [comment]
As for the `preferred-citation` I couldn't see a way to have both proceedings listed, and I think they are both needed to give a complete picture, since the latter one has the more up-to-date description of the codebase's main features.

**Pull request merged**
