### PR TITLE
Steamlining ServiceX Executors

### PR DESCRIPTION
**Pull request by gordonwatts**
* Support both `parquet` and `root` datatype returns from ServiceX
* Support proper (better) flow of metadata through the system
* Fill in the `dataset` metadata automatically
* `dask_executor` is properly exported by the package
* Remove `FuncAdlDataset` from the package - its functionality is directly supported by the `servicex` package now.
* Remove `uproot` open file hack required to work around an old (now fixed) bug in `uproot` on windows.
* Add a `title` argument to the `execute` method that can be used to track the queries up on the backend and in the local progress bars.
* Use new `dict` way of declaring columns - should be more readable (the example jupyter notebooks have been updated).

Note on testing:

* This requires the new backend code gen to be running in `ServiceX`.

This is a WIP until the following two things:

* [x] Beta versions of packages are released
* [x] ServiceX has released the new C++ code generators
* [x] @BenGalewsky reviews this for `funcX` compatibility

### CODE REVIEW

**Comment by lgray** [comment]
@gordonwatts can you please try to minimize rendered images in notebook (unless meant for documentation, of course). They otherwise cause unnecessary repository bloat.

**Comment by gordonwatts** [comment]
I believe there is one image per notebook. We could upload the notebook with no images if you like, but it means looking them in the repo will not make that much sense.

The notebooks are demos that can be run to show how this works. So they are documentation and also... not. We could eliminate all outputs if you like. Please let us know what is the norm in the repo, @lgray !

**Comment by lgray** [comment]
OK - just making sure you didn't upload randomly evaluated notebooks. Notebooks with images for documentation are absolutely fine!

**Comment by lgray** [comment]
@gordonwatts There's a refactor/rewrite of executor going on in #557 that you may want to be mindful of.

**Comment by gordonwatts** [comment]
Thanks for the warning. I have no idea what the slotting is. First I want to get sign off on these changes from @BenGalewsky .

**Review by BenGalewsky — APPROVED** [review]
Ready for Prime Time!

**Comment by lgray** [comment]
@gordonwatts ready for merging?

**Pull request merged**
