### PR TITLE
fix(wq): count chunks metric fix

### PR DESCRIPTION
**Pull request by btovar**
A couple of small wq fixes:

- Use the count of items processed to report number of chunks in "metrics".  Previous code tried to get a len of a generator, which is not defined.
- Also, ensure that that the parent of the staging directory exists.

### CODE REVIEW

**Comment by lgray** [comment]
Ah - this PR goes into the discussion re: TaskVine. Since the user interface we want to present to people from coffea 2023 onwards is dask-based. 

The semantics of file access, metrics, etc. are very different.

**Comment by lgray** [comment]
Changes will be coming to the executors soon.

**Comment by lgray** [comment]
~@btovar could you rebase this to latest master?~ I have done this for you!

**Comment by btovar** [comment]
Not used anymore.

**Pull request closed without merging**
