### PR TITLE
Ratio Plots

### PR DESCRIPTION
**Pull request by nsmith-**
Also patch conflict between category labels and `*` wildcards, fix warning in tests.

### CODE REVIEW

**Comment by nsmith-** [comment]
@mcremone this will fix the `Z+jets` issue as well

**Comment by lgray** [comment]
I'll make a new release after this one gets merged.

**Comment by nsmith-** [comment]
Feel free to do so once tests pass

**Comment by lgray** [comment]
@mcremone now in v0.2.4 from pip, etc.

**Pull request merged**
