### PR TITLE
move ipywidgets to spark spec. (reduce bloat)

### PR DESCRIPTION
**Pull request by lgray**
As in title.

I think @perilousapricot requested this for easy packaging in his cluster. 
I've set it up so that `pip install coffea[spark]` with spark already installed will do the same thing, that should be manageable?
Let me know if not, otherwise I'd just kinda prefer people `pip install coffea ipywidgets` if they need it like that.

This chops a little over 100MB off the install size for coffea and appropriately factorizes coffea from jupyter/ipython.

### CODE REVIEW

**Comment by PerilousApricot** [comment]
:+1: thanks

**Comment by nsmith-** [comment]
Added in #259, looks like it was something to do with `tqdm`?

**Comment by lgray** [comment]
Yeah some ipy-kernel install business @PerilousApricot was doing triggered this.

Just to be clear: @PerilousApricot do you want `pip install coffea[spark]` to give you `ipywidgets` or do you wanna explicitly do `pip install coffea ipywidgets`?

**Comment by PerilousApricot** [comment]
It's not a spark issue, per-se, (nick's comment reminded me). It's that
tqdm in a jupyter session will (was?) unconditionally try to use ipywidgets
and bombing even if it wasn't installed. I guess it's technically a bug in
TQDM? I'm pretty sure I put in an issue back when I first ran into it, but
I don't remember a resolution to it.

>

**Comment by lgray** [comment]
I mean on our side we just stuck ipywidgets in coffea. :D

I'm happy to leave it in the `[spark]` specialization. Just remember to update your build scripts. If you change to `pip install coffea[spark]` now it'll be seamless when the new version comes on Sept. 3rd.

**Pull request merged**
