### PR TITLE
fix: make `.metric_table()` and `.nearest()` work when `return_combinations` and `return_metric` are set to `True` respectively 

### PR DESCRIPTION
**Pull request by ikrommyd**
This PR aims to make `.metric_table()` and `.nearest` work when `return_combinations` and `return_metric` are set to `True`.
The somewhat "correct" structure should be there but apparently there is something fishy when computing the output of `metric_table` using `dask.compute()` and also `.nearest` now fails at the `out = awkward.firsts(b[mmin], axis=axis + 1)` line with `dask_awkward.utils.DaskAwkwardNotImplemented: TODO` and it shouldn't. 
This is just a draft PR so that the devs can have access to this branch from the coffea repo.

### CODE REVIEW

**Comment by ikrommyd** [comment]
Tests are passing but it's not correct in delayed mode. DO NOT MERGE. This also got me thinking that maybe CI should check fundamental operations better

**Comment by lgray** [comment]
thanks for putting this together - I'll see what I can do to get to the bottom of it.

**Comment by ikrommyd** [comment]
Thanks! It's not really the most urgent thing but I guess it's just nice to have. Wouldn't it be also possible to do `map_partitions` of eager functions in the case where `self` and `other` are `dak` objects or am I missing a point here?

**Comment by lgray** [comment]
This PR is waiting on #926.

**Comment by lgray** [comment]
Testing it locally if I add in https://github.com/dask-contrib/dask-awkward/pull/424 then this all works just fine.

Could you write up some tests, taking that branch for dask-awkward.

We can merge this when dak 2023.11.5 or whatever is next comes out.

**Comment by ikrommyd** [comment]
@lgray `dak.firsts` only affects `.nearest` right? `.metric_table()` actually returns the dask-awkward arrays, but you can only compute them individually. Calling `dask.compute()` on the entire output of `metric_table` doesn't work. It complains about `TypeError: PlaceholderArray supports only trivial slices, not int64`. That's exactly how it was for me before you adapted it to the new interface.

**Comment by lgray** [comment]
`nearest`:
```
>>> dask.compute(events.Muon.nearest(events.Jet, return_metric=True))
((<JetArray [[], [], [], [], ..., [], [], [], []] type='40 * var * ?Jet[area:...'>, <Array [[], [], [], [], [...], ..., [], [], [], []] type='40 * var * ?float32'>),)
```

`metric_table`:
```
>>> dask.compute(events.Muon.metric_table(events.Jet, return_combinations=True))
((<Array [[], [], [], [], ..., [], [], [], []] type='40 * var * var * float32'>, (<MuonArray [[], [], [], [], ..., [], [], [], []] type='40 * var * var * Muo...'>, <JetArray [[], [], [], [], ..., [], [], [], []] type='40 * var * var * Jet[...'>)),)
```

Seems to be ok on the `nano_dy.root`. You'll need dask-awkward main installed locally to have this outcome.

**Comment by ikrommyd** [comment]
why doesn't `dask.compute(events.Electron.metric_table(events.TrigObj, return_combinations=True))` work for me? Muons and TrigObjs work. Why not Electrons?

**Comment by ikrommyd** [comment]
eager computation works for Electrons and TrigObjs

**Comment by lgray** [comment]
So it comes down to:
```
>>> table, (es, objs) = events.Electron.metric_table(events.TrigObj, return_combinations=True)
>>> dask.compute((table,  objs))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/highlevel.py", line 1288, in __repr__
    return self._repr(80)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/highlevel.py", line 1314, in _repr
    valuestr = valuestr + " " + awkward._prettyprint.valuestr(self, 1, strwidth)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 350, in valuestr
    _, strs = valuestr_horiz(data, limit_cols, formatter)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 154, in valuestr_horiz
    cols_taken, strs = valuestr_horiz(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 144, in valuestr_horiz
    cols_taken, strs = valuestr_horiz(get_at(data, 0), limit_cols, formatter)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 154, in valuestr_horiz
    cols_taken, strs = valuestr_horiz(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 229, in valuestr_horiz
    get_field(data, key), target, formatter
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 89, in get_field
    out = data._layout._getitem_field(field)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/record.py", line 191, in _getitem_field
    return self._array._getitem_field(where)._getitem_at(self._at)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/contents/numpyarray.py", line 317, in _getitem_at
    out = self._data[where]
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_nplikes/placeholder.py", line 97, in __getitem__
    raise TypeError(
TypeError: PlaceholderArray supports only trivial slices, not int64
```

So it's something in that particular combination that's causing some touching to be wrong, I suspect. However if I try each field of `events.TrigObj` individually they all succeed. Trying more combinations.

**Comment by lgray** [comment]
Even `dask.compute((table,  objs[['pt','eta','phi', 'l1pt', 'l1pt_2', 'l2pt', 'id', 'l1iso', 'l1charge', 'filterBits']]))` (this is functionally the same object but making a slice that picks all the fields) functions fine.

This smells like an awkward bug where but the essential nature of it is hidden pretty deep.

**Comment by ikrommyd** [comment]
This was the exact same error I had when I dmed you in Slack about it.
I added a test that should be passing once we get a new dask-awkward patch. Hope you don't mind making use of dask-awkward's `assert_eq` test util

**Comment by lgray** [comment]
I know it's the same error. I am exploring it because I finally have some time to.

**Comment by lgray** [comment]
@agoose77 Could use your help here.
You'll need to take dask-awkward and this branch of coffea, but we see a crash in awkward when trying to `dask.compute` ( and print) certain branches.

Notably:
```
_ = dask.compute(events.Electron.metric_table(events.TrigObj, return_combinations=True))
```
works but if you let it print the result in the repl:
```
>>> dask.compute(events.Electron.metric_table(events.TrigObj, return_combinations=True))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/highlevel.py", line 1288, in __repr__
    return self._repr(80)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/highlevel.py", line 1314, in _repr
    valuestr = valuestr + " " + awkward._prettyprint.valuestr(self, 1, strwidth)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 350, in valuestr
    _, strs = valuestr_horiz(data, limit_cols, formatter)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 154, in valuestr_horiz
    cols_taken, strs = valuestr_horiz(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 144, in valuestr_horiz
    cols_taken, strs = valuestr_horiz(get_at(data, 0), limit_cols, formatter)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 154, in valuestr_horiz
    cols_taken, strs = valuestr_horiz(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 229, in valuestr_horiz
    get_field(data, key), target, formatter
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 89, in get_field
    out = data._layout._getitem_field(field)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/record.py", line 191, in _getitem_field
    return self._array._getitem_field(where)._getitem_at(self._at)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/contents/numpyarray.py", line 317, in _getitem_at
    out = self._data[where]
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_nplikes/placeholder.py", line 97, in __getitem__
    raise TypeError(
TypeError: PlaceholderArray supports only trivial slices, not int64
```

**Comment by lgray** [comment]
@iasonkrom it appears is a legitimate awkward-array error. You should explore these bugs deeper, often there is a clear answer that's easy to find!

**Comment by lgray** [comment]
Here's more evidence that it is in awkward array:
```
>>> table, (es, objs) = events.Electron.metric_table(events.TrigObj, return_combinations=True)
>>> out1, out2 = dask.compute(table, objs)
>>> out1
<Array [[], [[0.0224, ..., 2.23]], ..., [], []] type='40 * var * var * float32'>
>>> out2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/highlevel.py", line 1288, in __repr__
    return self._repr(80)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/highlevel.py", line 1314, in _repr
    valuestr = valuestr + " " + awkward._prettyprint.valuestr(self, 1, strwidth)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 350, in valuestr
    _, strs = valuestr_horiz(data, limit_cols, formatter)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 154, in valuestr_horiz
    cols_taken, strs = valuestr_horiz(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 144, in valuestr_horiz
    cols_taken, strs = valuestr_horiz(get_at(data, 0), limit_cols, formatter)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 154, in valuestr_horiz
    cols_taken, strs = valuestr_horiz(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 229, in valuestr_horiz
    get_field(data, key), target, formatter
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 89, in get_field
    out = data._layout._getitem_field(field)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/record.py", line 191, in _getitem_field
    return self._array._getitem_field(where)._getitem_at(self._at)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/contents/numpyarray.py", line 317, in _getitem_at
    out = self._data[where]
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_nplikes/placeholder.py", line 97, in __getitem__
    raise TypeError(
TypeError: PlaceholderArray supports only trivial slices, not int64
```

**Comment by lgray** [comment]
In particular this error seems to be coming from combinations exploded TrigObj.pt:
```
>>> #continuing from above
>>> out2[[field for field in out2.fields]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/highlevel.py", line 1288, in __repr__
    return self._repr(80)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/highlevel.py", line 1314, in _repr
    valuestr = valuestr + " " + awkward._prettyprint.valuestr(self, 1, strwidth)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 350, in valuestr
    _, strs = valuestr_horiz(data, limit_cols, formatter)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 154, in valuestr_horiz
    cols_taken, strs = valuestr_horiz(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 144, in valuestr_horiz
    cols_taken, strs = valuestr_horiz(get_at(data, 0), limit_cols, formatter)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 154, in valuestr_horiz
    cols_taken, strs = valuestr_horiz(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 229, in valuestr_horiz
    get_field(data, key), target, formatter
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 89, in get_field
    out = data._layout._getitem_field(field)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/record.py", line 191, in _getitem_field
    return self._array._getitem_field(where)._getitem_at(self._at)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/contents/numpyarray.py", line 317, in _getitem_at
    out = self._data[where]
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_nplikes/placeholder.py", line 97, in __getitem__
    raise TypeError(
TypeError: PlaceholderArray supports only trivial slices, not int64
>>> out2[[field for field in out2.fields if field != "pt"]]
<Array [[], [[{eta: 1.82, ...}, ...]], ..., []] type='40 * var * var * {eta...'>
```

So maybe the form is getting packed up wrong somewhere in dask awkward as well?

**Comment by lgray** [comment]
Just to summarize: this appears to be in the dask-awkward or awkward side of things. My guess of what's happening is that for certain combinations of outputs the column optimization is giving a somewhat wrong answer and that ends up with some fields not being filled correctly on computation.

**Comment by lgray** [comment]
I cannot yet make a simple reproducer.

My other perspective on this is that it is not often that people will be computing the whole post-combinations output in an actual analysis, even when considering functions it'll be functions of a few variables of the outputs which compute just fine. So I suspect the actual failure rate of this in practice is low.

However, it is causing a really strange outcome if you ask for that computation and it should be fixed.

**Comment by lgray** [comment]
More interestingness, it's always the second item in the list, if I switch `Electron` and `TrigObj` in the matching suddenly electrons has the problem.

**Comment by lgray** [comment]
@iasonkrom can you take a look at the test? the assert is failing for some reason but I'm in meetings right now!

**Comment by agoose77** [comment]
@douglasdavis I meant to mention this in the meeting — I think this might be a dask-awkward bug whereby `dask.compute(X, Y)` doesn't lead to `Y` being properly touched. That sounds vaguely familiar as something we already addressed. Any thoughts? :)

**Comment by ikrommyd** [comment]
whoopsie, I forgot `.nearest` reuturns 2 and not 3 things. Should be fixed now as they are passing locally. I also changed the test them to use `Electron` and `TrigObj` which is where we see the bug

**Comment by ikrommyd** [comment]
hmm now they actually fail even in the `assert_eq` because of the bug. Let me play around a bit.

**Comment by ikrommyd** [comment]
@lgray it gets weirder.
```
 dask.compute(*daskevents.Electron.metric_table(daskevents.TrigObj, return_combinations=True))
 ```
 fails instantly in repl.
 look at Muons and Jets now:
 ```
 In [5]:  dask.compute(*daskevents.Muon.metric_table(daskevents.Jet, return_combinations=True))                                                                                                                                                                                                    
Out[5]:                                                                                                                                                                                                                                                                                           
(<Array [[], [], [], [], ..., [], [], [], []] type='40 * var * var * float32'>,                                                                                                                                                                                                                   
 (<MuonArray [[], [], [], [], ..., [], [], [], []] type='40 * var * var * Muo...'>,                                                                                                                                                                                                               
  <JetArray [[], [], [], [], ..., [], [], [], []] type='40 * var * var * Jet[...'>))                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                  
In [6]: mval, (a,b) =  dask.compute(*daskevents.Muon.metric_table(daskevents.Jet, return_combinations=True))                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                  
In [7]: a                                                                                                                                                                                                                                                                                         
Out[7]: ---------------------------------------------------------------------------                                                                                                                                                                                                               
TypeError                                 Traceback (most recent call last)                                                        
```
This fails when you actually try to view "a" or "b" in repl

When testing, even if I test with muons and jets,
```python
import dask
from dask_awkward.lib.testutils import assert_eq

from coffea.nanoevents import NanoEventsFactory

eagerevents = NanoEventsFactory.from_root(
    {"tests/samples/nano_dy.root": "Events"},
    delayed=False,
).events()

daskevents = NanoEventsFactory.from_root(
    {"tests/samples/nano_dy.root": "Events"},
    delayed=True,
).events()

mval_eager, (a_eager, b_eager) = eagerevents.Muon.metric_table(
    eagerevents.Jet, return_combinations=True
)
mval_dask, (a_dask, b_dask) = dask.compute(
    *daskevents.Muon.metric_table(daskevents.Jet, return_combinations=True)
)
assert_eq(mval_eager, mval_dask)
assert_eq(a_eager, a_dask)
assert_eq(b_eager, b_dask)
```
this fails at the `assert_eq(a_eager, a_dask)` line

**Comment by ikrommyd** [comment]
Here is the error message also:
```python
AssertionError                            Traceback (most recent call last)
Cell In[1], line 23
     19 mval_dask, (a_dask, b_dask) = dask.compute(
     20     *daskevents.Muon.metric_table(daskevents.Jet, return_combinations=True)
     21 )
     22 assert_eq(mval_eager, mval_dask)
---> 23 assert_eq(a_eager, a_dask)
     24 assert_eq(b_eager, b_dask)

File ~/fun/coffea_dev/.venv/lib/python3.10/site-packages/dask_awkward/lib/testutils.py:37, in assert_eq(a, b, check_forms, check_divisions, scheduler, **kwargs)
     35 scheduler = scheduler or DEFAULT_SCHEDULER
     36 if isinstance(a, (Array, ak.Array)):
---> 37     assert_eq_arrays(
     38         a,
     39         b,
     40         check_forms=check_forms,
     41         check_divisions=check_divisions,
     42         scheduler=scheduler,
     43         **kwargs,
     44     )
     45 elif isinstance(a, (Record, ak.Record)):  # type: ignore
     46     assert_eq_records(a, b, scheduler=scheduler, **kwargs)

File ~/fun/coffea_dev/.venv/lib/python3.10/site-packages/dask_awkward/lib/testutils.py:67, in assert_eq_arrays(a, b, isclose_equal_nan, check_forms, check_divisions, scheduler, convert_to_lists)
     64 b_comp = b.compute(scheduler=scheduler) if b_is_coll else b
     66 a_tt = typetracer_array(a)
---> 67 b_tt = typetracer_array(b)
     68 assert a_tt is not None
     69 assert b_tt is not None

File ~/fun/coffea_dev/.venv/lib/python3.10/site-packages/dask_awkward/lib/core.py:2390, in typetracer_array(a)
   2387     return a._meta
   2388 elif isinstance(a, ak.Array):
   2389     return ak.Array(
-> 2390         a.layout.to_typetracer(forget_length=True),
   2391         behavior=a._behavior,
   2392         attrs=a._attrs,
   2393     )
   2394 else:
   2395     msg = (
   2396         "`a` should be an awkward array or a Dask awkward collection.\n"
   2397         f"Got type {type(a)}"
   2398     )

File ~/fun/coffea_dev/.venv/lib/python3.10/site-packages/awkward/contents/content.py:275, in Content.to_typetracer(self, forget_length)
    274 def to_typetracer(self, forget_length: bool = False) -> Self:
--> 275     return self._to_typetracer(forget_length)

File ~/fun/coffea_dev/.venv/lib/python3.10/site-packages/awkward/contents/listoffsetarray.py:230, in ListOffsetArray._to_typetracer(self, forget_length)
    226 def _to_typetracer(self, forget_length: bool) -> Self:
    227     offsets = self._offsets.to_nplike(TypeTracer.instance())
    228     return ListOffsetArray(
    229         offsets.forget_length() if forget_length else offsets,
--> 230         self._content._to_typetracer(forget_length),
    231         parameters=self._parameters,
    232     )

File ~/fun/coffea_dev/.venv/lib/python3.10/site-packages/awkward/contents/listoffsetarray.py:230, in ListOffsetArray._to_typetracer(self, forget_length)
    226 def _to_typetracer(self, forget_length: bool) -> Self:
    227     offsets = self._offsets.to_nplike(TypeTracer.instance())
    228     return ListOffsetArray(
    229         offsets.forget_length() if forget_length else offsets,
--> 230         self._content._to_typetracer(forget_length),
    231         parameters=self._parameters,
    232     )

File ~/fun/coffea_dev/.venv/lib/python3.10/site-packages/awkward/contents/indexedarray.py:243, in IndexedArray._to_typetracer(self, forget_length)
    239 def _to_typetracer(self, forget_length: bool) -> Self:
    240     index = self._index.to_nplike(TypeTracer.instance())
    241     return IndexedArray(
    242         index.forget_length() if forget_length else index,
--> 243         self._content._to_typetracer(forget_length),
    244         parameters=self._parameters,
    245     )

File ~/fun/coffea_dev/.venv/lib/python3.10/site-packages/awkward/contents/recordarray.py:370, in RecordArray._to_typetracer(self, forget_length)
    368 def _to_typetracer(self, forget_length: bool) -> Self:
    369     backend = TypeTracerBackend.instance()
--> 370     contents = [x._to_typetracer(forget_length) for x in self._contents]
    371     return RecordArray(
    372         contents,
    373         self._fields,
   (...)
    376         backend=backend,
    377     )

File ~/fun/coffea_dev/.venv/lib/python3.10/site-packages/awkward/contents/recordarray.py:370, in <listcomp>(.0)
    368 def _to_typetracer(self, forget_length: bool) -> Self:
    369     backend = TypeTracerBackend.instance()
--> 370     contents = [x._to_typetracer(forget_length) for x in self._contents]
    371     return RecordArray(
    372         contents,
    373         self._fields,
   (...)
    376         backend=backend,
    377     )

File ~/fun/coffea_dev/.venv/lib/python3.10/site-packages/awkward/contents/numpyarray.py:225, in NumpyArray._to_typetracer(self, forget_length)
    223 def _to_typetracer(self, forget_length: bool) -> Self:
    224     backend = TypeTracerBackend.instance()
--> 225     data = self._raw(backend.nplike)
    226     return NumpyArray(
    227         data.forget_length() if forget_length else data,
    228         parameters=self._parameters,
    229         backend=backend,
    230     )

File ~/fun/coffea_dev/.venv/lib/python3.10/site-packages/awkward/contents/numpyarray.py:199, in NumpyArray._raw(self, nplike)
    198 def _raw(self, nplike=None):
--> 199     return to_nplike(self.data, nplike, from_nplike=self._backend.nplike)

File ~/fun/coffea_dev/.venv/lib/python3.10/site-packages/awkward/_nplikes/__init__.py:41, in to_nplike(array, nplike, from_nplike)
     36 if isinstance(from_nplike, awkward._nplikes.cupy.Cupy) and not isinstance(
     37     nplike, awkward._nplikes.cupy.Cupy
     38 ):
     39     array = array.get()  # type: ignore[attr-defined]
---> 41 return nplike.asarray(array)

File ~/fun/coffea_dev/.venv/lib/python3.10/site-packages/awkward/_nplikes/typetracer.py:658, in TypeTracer.asarray(self, obj, dtype, copy)
    651 def asarray(
    652     self,
    653     obj,
   (...)
    656     copy: bool | None = None,
    657 ) -> TypeTracerArray:
--> 658     assert not isinstance(obj, PlaceholderArray)
    660     if dtype is not None:
    661         dtype = np.dtype(dtype)

AssertionError: 

```

**Comment by lgray** [comment]
OK - then we need to characterize this issue further.

**Comment by lgray** [comment]
So for sure this problem is in dask_awkward because it works when I turn off column optimization. @douglasdavis

Though for some reason the Jets don't pass the `assert_eq`.

**Comment by agoose77** [comment]
This error looks like the same symptom - somehow you're getting placeholders in computed results. This should not happen.

**Comment by ikrommyd** [comment]
> Though for some reason the Jets don't pass the assert_eq.

Oh maybe `assert_eq` doesn't work with coffea objects? `a` and `b` are actually `40 * var * var * Muon` while the rest have some ragged structure but it's `*float32` in the end

**Comment by lgray** [comment]
It passes for muons but somehow the jet dtypes are different.

**Comment by lgray** [comment]
It's hard to figure out what's up because the Jet dtype is eight miles long.

**Comment by lgray** [comment]
In particular it's muonIdxG's dtype that is different... 😵‍💫

**Comment by lgray** [comment]
So, indeed:
```
>>> print(ak.type(b_eager["muonIdxG"]))
40 * var * var * var * int64[parameters={"__doc__": "index of first matching muon"}]
>>> print(ak.type(b_dask["muonIdxG"]))
40 * var * var * [var * int64[parameters={"__doc__": "index of first matching muon"}], parameters={"__doc__": "index of first matching muon"}]
```

The dtypes are different, which is what is causing the non-closure, but the values, if you compare the arrays directly are all the same.

I think the extra parameters are a nanoevents bug and I'll dig into that, however, clearly, this isn't something we should hold up this PR for.

Aside from the fact that this only works with column optimization turned off, which we can do in the test for now until fixed upstream.

I believe it is *highly* unlikely someone runs into this in real analysis scenarios.

**Comment by ikrommyd** [comment]
shall I set column optimization off in the test and change this to ready for review?

**Comment by lgray** [comment]
@iasonkrom yep! looks good - I just added a note for ourselves for the future so we tighten the thumbscrews when we are able to.

**Comment by douglasdavis** [comment]
I'm trying to catch up on what's going on here, but it looks like column optimization is missing a necessary column and therefore putting in a placeholder array in a spot where we would expect a concrete array?

**Comment by lgray** [comment]
@douglasdavis exactly

I can cook you a minimal repro that involves coffea, I just haven't had the time to boil it down.

**Pull request merged**
