### PR TITLE
Metrics for uproot

### PR DESCRIPTION
**Pull request by nsmith-**

### CODE REVIEW

**Comment by nsmith-** [comment]
@mcremone here are those metrics.  Add `'savemetrics': True` to `executor_args` to enable.
(maybe I should update the docstring)

**Comment by lgray** [comment]
@nsmith- merge?

**Comment by lgray** [comment]
As soon as #116 passes I'll rebase on that to grab the passing tests to make sure nothing gets clobbered. Then I'll merge.

**Comment by nsmith-** [comment]
cool thanks

**Pull request merged**
