### PR TITLE
fix: make `apply_to_fileset` be able to handle tuple outputs of `data_manipulation`.

### LINKED ISSUE #1037: `apply_to_fileset` should be able to handle tuple outputs of `data_manipulation`
```python
fileset = {
    "ZJets": {
        "files": {
            "https://github.com/CoffeaTeam/coffea/raw/master/tests/samples/nano_dy.root": "Events",
        }
    }
}

def my_analysis(events):
    e = events.Electron
    m = events.Muon
    t = events.Tau
    return e, m, t

to_compute = apply_to_fileset(
    my_analysis,
    fileset,
    schemaclass=NanoAODSchema,
    uproot_options={"allow_read_errors_with_report": False},
)

to_compute
```
fails with
```python
File ~/miniforge3/envs/egamma_dev/lib/python3.10/site-packages/coffea/dataset_tools/apply_processor.py:129, in apply_to_fileset(data_manipulation, fileset, schemaclass, uproot_options)
    125 dataset_out = apply_to_dataset(
    126     data_manipulation, dataset, schemaclass, metadata, uproot_options
    127 )
    128 if isinstance(dataset_out, tuple):
--> 129     out[name], report[name] = dataset_out
    130 else:
    131     out[name] = dataset_out

ValueError: too many values to unpack (expected 2)
```
if you try to return two things, Electrons and Muons for instance, this will think the Muons are the report and will return
```
({'ZJets': dask.awkward<Electron, npartitions=1>},
 {'ZJets': dask.awkward<Muon, npartitions=1>}
 ```
instead of
```
{'ZJets': (dask.awkward<Electron, npartitions=1>,
   dask.awkward<Muon, npartitions=1>)}
  ```
`apply_to_fileset` should somehow understand whether the returned tuple is of the form `(out, report)` or if out is just a `tuple`

### PR DESCRIPTION
**Pull request by ikrommyd**
Fixes https://github.com/CoffeaTeam/coffea/issues/1037

### CODE REVIEW

**Comment by lgray** [comment]
@iasonkrom please extend the tests to check this fix

**Comment by ikrommyd** [comment]
Added a new test. I don't know if you think this is too much testing but it does the job I believe.

**Comment by lgray** [comment]
For sure you don't need to compute and check those values. The consistency of compute is assured by a variety of other tests in coffea and elsewhere. Mostly compute just takes time and the tests are already lengthy.

**Comment by ikrommyd** [comment]
changed it to just checking lengths and types without computing

**Pull request merged**
