### PR TITLE
feat: `modifier` argument for `partial_weights` method

### PR DESCRIPTION
**Pull request by rkansal47**
Allows for a modifier when selecting a subset of weights in the `Weights` class.

### CODE REVIEW

**Review by nsmith- — APPROVED** [review]
Looks good to me! Do we need a 0.7 backport?

**Comment by lgray** [comment]
Can you give an example of usage? This seems niche or possibly confusing as written.

**Comment by lgray** [comment]
Another way to put this is why isn't this covered by appropriate definition of include or exclude? 
A more concise/correct API is better than stapling new parts to it.

**Comment by rkansal47** [comment]
@lgray my use case is separating the variations which should preserve the normalization and those which don't. i.e. I want to select the subset of weights which should preserve the normalization, and then normalize the variations of those weights.

**Comment by rkansal47** [comment]
Is there a way to do this with the current API?

**Comment by lgray** [comment]
@nsmith- since you designed this you know better, but shouldn't this be covered by something like:
```python3
weights.partial_weights(include=["norm_preserving", "modifier"], exclude=["norm_modifying"])
```
?

**Comment by lgray** [comment]
Oh, I see what's going on, yeah this is fine then.

**Pull request merged**
