### PR TITLE
Fix jec name splitting for regrouped uncertainties

### PR DESCRIPTION
**Pull request by pfackeldey**
Dear coffea developers,

this PR adds the possibility to use the regrouped jes uncertainties, which are a reduced set of the factorized uncertainties: https://twiki.cern.ch/twiki/bin/view/CMS/JECUncertaintySources#Run_2_reduced_set_of_uncertainty . 

The changes consist of:
- the name starts with "Regrouped", which has to be removed
- some regrouped uncertainties have a "_" in their name (*), which causes them to be splitted. They are stitched together again.

I've tested this code successfully using the reduced jes uncertainties txt file for 2017: https://twiki.cern.ch/twiki/pub/CMS/JECUncertaintySources/Regrouped_Fall17_17Nov2017_V32_MC_UncertaintySources_AK4PFchs.txt 

(*) uncertainties(2017): ['Absolute', 'Absolute_2017', 'BBEC1', 'BBEC1_2017', 'EC2', 'EC2_2017', 'FlavorQCD', 'HF', 'HF_2017', 'RelativeBal', 'RelativeSample_2017'] + 'Total'

Thank you very much for reviewing!

Best, Peter

### CODE REVIEW

**Comment by lgray** [comment]
@pfackeldey can you clean up the gripes from the linter? Thanks!

**Comment by pfackeldey** [comment]
@lgray done.
For some reason one of the test cases seems to get stuck though...

**Comment by lgray** [comment]
@pfackeldey Yeah the osx containers get stuck for some reason from time to time.

Could you add a test that confirms this works as expected?

I think once that is there we're done!

**Comment by pfackeldey** [comment]
@lgray I've added a test case. I made it similar to the normal junc test case.

**Comment by lgray** [comment]
Thanks a lot! I'll merge this when tests come through.

**Comment by pfackeldey** [comment]
Thank you :)

**Pull request merged**
