### PR TITLE
build: pin up to awkward 2.4.8, dask-awkward 2023.11.0

### PR DESCRIPTION
**Pull request by lgray**

### CODE REVIEW

**Comment by lgray** [comment]
@agoose77 new error popped up in workqueue tests ```ValueError: defined_divisions only works when divisions are known.```

**Comment by agoose77** [comment]
@douglasdavis would you be able to take a peek at this?

**Comment by lgray** [comment]
same error in the normal CI! so should be easy to pin down.

**Comment by lgray** [comment]
sigh guess I can't just do that. annoying.

**Comment by agoose77** [comment]
@lgray you can permit direct references with 
```yaml
[tool.hatch.metadata]
allow-direct-references = true
```

**Comment by lgray** [comment]
cool so we just need a new dask-awkward release and a repin @agoose77

**Comment by douglasdavis** [comment]
> cool so we just need a new dask-awkward release and a repin @agoose77

`2023.11.0` is on PyPI!

**Pull request merged**
