### PR TITLE
fix: convert sys.exit(1) to ValueError in DataDiscoveryCLI

### PR DESCRIPTION
**Pull request by ikrommyd**
I was getting `NameError: name 'exit' is not defined` from these statments and not a proper exit.

### CODE REVIEW

**Comment by lgray** [comment]
Shouldn't this raise an exception instead? `sys.exit` can't be handled by any code that calls this class.

**Comment by ikrommyd** [comment]
Yeah probably. I believe @valsdav was thinking actual cli here. I'll change it to whatever y'all want

**Comment by valsdav** [comment]
Hi! right, better to raise an exception there!

**Comment by ikrommyd** [comment]
Then converting the print statement to a ValueError should be good for both in-script/notebook and cli use

**Pull request merged**
