### PR TITLE
Revert "Fix Cornercases: Empty formula and multiple formulas for btag SF"

### PR DESCRIPTION
**Pull request by lgray**
Reverts CoffeaTeam/coffea#276

The fix causes another bug.

### CODE REVIEW

**Comment by lgray** [comment]
@pfackeldey The fix you provided stalls on the Legacy btag SFs.

Can you please provide a functioning test of the patch?

**Comment by pfackeldey** [comment]
@lgray Could you point me to the Legacy btag SFs? I will try then to provide a functioning test of the patch. Thank you :)

**Comment by lgray** [comment]
@pfackeldey Try out https://github.com/CoffeaTeam/coffea/blob/master/tests/samples/DeepCSV_2016LegacySF_V1_TuneCP5.btag.csv.gz

Thanks!

**Comment by pfackeldey** [comment]
@lgray For me it works for the legacy btag SFs

```python
from coffea.lookup_tools import csv_converters
sfs=csv_converters.convert_btag_csv_file("tests/samples/DeepCSV_2016LegacySF_V1_TuneCP5.btag.csv.gz")
```
works for me (just takes a few minutes)

**Comment by lgray** [comment]
OK - then it was so slow I gave up. If it doesn't parse in a few seconds there's pretty much no reason to use this over the Pandas implementation. I guess that's just a huge file?

**Comment by pfackeldey** [comment]
Yes exactly. That was why I "precompiled" those corrections and saved the evaluator in a `.coffea` file in my analysis. But I also switched to the Pandas implementation, which is way faster.

**Comment by lgray** [comment]
Yeesh, someone felt the kitchen sink was needed.
Very well. 

I'll instead hook Nick's stuff into the evaluator / extractor schema, add a deprecation warning for this.

Thanks!

**Pull request merged**
