### PR TITLE
Use `fsspec` to open `parquet` files in nanoevents factory

### PR DESCRIPTION
**Pull request by gordonwatts**
* Enable alternate file sources for `parquet` files, like `file://...` and 'http://...` for the `from_parquet` class method of `nanoevents`.

Approach:
* Take advantage of the `fsspec` library, which is already included in the `coffea` distribution (pulled in, I think, by `pyarrow`.

This is a draft until:
* [x] Externally test that other URI's (like `http://...`) work.

### CODE REVIEW

**Comment by lgray** [comment]
@gordonwatts this otherwise looks fine - flip it to ready for review when you are good to go.

**Comment by gordonwatts** [comment]
Sorry - I *really* took the weekend off. I'll get back to this.

**Comment by gordonwatts** [comment]
Despite a number of obstacles, this is now ready to merge from my side!

**Comment by lgray** [comment]
Looks good to me - merging it!

**Comment by gordonwatts** [comment]
Thank you!!!

**Comment by nsmith-** [comment]
This reminds me that we are still missing an fsspec-xrootd implementaiton, which would unlock a lot of functionality very easily.

**Pull request merged**
