### PR TITLE
feat: use new dask methods

### PR DESCRIPTION
**Pull request by agoose77**
Leverages dask-contrib/dask-awkward#409

### CODE REVIEW

**Comment by lgray** [comment]
@agoose77 this is in the right direction but there's one big problem in that now iterated `__getattr__` seems to not be supported:

repro:
```python3
from coffea.nanoevents import NanoEventsFactory
events = NanoEventsFactory.from_root(
    "tests/samples/nano_dy.root:Events",
).events()

events.Jet.matched_muons.matched_jet
```

now fails with:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute 'matched_jet'
```

**Comment by lgray** [comment]
@agoose77 

Still running into some regressions:
```
pytest tests/test_nanoevents_pfnano.py tests/test_nanoevents_physlite.py
```

results in a couple failed tests with:
```
TypeError: meta must be an instance of an Awkward Array, not <class 'dask_awkward.lib.core.Array'>.
```
and
```
NotImplementedError: 
```

Which were not encountered before!

**Comment by lgray** [comment]
@agoose77 ok this last edit gets rid of all the regressions on my side.

**Comment by agoose77** [comment]
OK, let's look to merging this in dask-awkward, then :)

**Comment by lgray** [comment]
@agoose77 is there any way we can make it so I don't have to repeat functions like metadata that access awkward-array information but don't need dask? That seems rather pesky.

**Comment by agoose77** [comment]
@lgray sure! Let me think about it.

**Comment by agoose77** [comment]
@lgray try this (with new dask-awkward in my branch)

**Comment by lgray** [comment]
all green in local tests.

**Comment by lgray** [comment]
Once all that gets merged I'll finally switch nanoevents to use transient attrs and can get rid of that nasty copyreg I use right now. Woo.

**Pull request merged**
