### PR TITLE
build: try ak 2.4.7

### PR DESCRIPTION
**Pull request by lgray**
just to check. @agoose77

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Do you have an idea why `coffea` tests fail with awkward 2.4.7 ?

**Comment by agoose77** [comment]
Yes — we (Awkward) introduced a dependency upon NumPy 1.24+ without our metadata describing this. We've yanked the release, and are working on a new release of 2.4.8

**Comment by lgray** [comment]
@GaetanLepage awkward 2.4.7 had unexpected bugs related to numpy and was yanked on PyPI https://pypi.org/project/awkward/#history. You should uninstall it if you have it locally.

**Comment by GaetanLepage** [comment]
Oh ! Good to know, thanks !

**Pull request closed without merging**
