### PR TITLE
Allow specification of axes by positional list or by kwarg sequence

### PR DESCRIPTION
**Pull request by lgray**
This was brought up in discussions with @andrzejnovak / @kratsg / @nsmith- that syntax like:
```
h = coffea.hist.Hist("Observed bird count",
                     axes=(coffea.hist.Cat("species", "Bird species"),
                           coffea.hist.Bin("x", "x coordinate [m]", 20, -5, 5),
                           coffea.hist.Bin("y", "y coordinate [m]", 20, -5, 5),
                           )
                     )
```

is much more clear to new users than the positional list syntax that we've been using so far.

This PR allows both styles of histogram instantiation.

### CODE REVIEW

**Comment by nsmith-** [comment]
Would `hist.Hist(hist.Bin(...), ..., label='event count')` be more palatable?

**Comment by lgray** [comment]
@nsmith- I think the main confusion was over the meaning of the axes and categories (as in they didn't know what kind of histogram they were building). It would make sense to let the label be possibly kwargs. I'll add that too.

**Comment by lgray** [comment]
and so `hist.Hist(hist.Bin(...), ..., label='event count')` is already possible anyway so that's good.

**Comment by lgray** [comment]
@nsmith- anything else before I merge this?

**Pull request merged**
