### PR TITLE
Add tests against python 3.8

### PR DESCRIPTION
**Pull request by lgray**
As in title.

### CODE REVIEW

**Comment by lgray** [comment]
Hmm wheels for scipy not available yet...

**Comment by nsmith-** [comment]
I think 3.6 is going to take some time to remove.  It's the latest LCG python.

**Comment by lgray** [comment]
Yeah, fair enough, guess we'll just have more tests for a while.

Makes a good point to move to azure pipelines more free jobs.

**Comment by lgray** [comment]
Some slow improvement here: numpy and scipy now have wheels, waiting on numba and llvmlite now!

**Comment by nsmith-** [comment]
Is there any reason to drop 3.6?

**Comment by lgray** [comment]
Nope and it's not since I rebased it.

pyarrow is still missing python 3.8 wheels, no good reason to add it yet.

**Comment by lgray** [comment]
Damn, pyarrow 0.16.0 is out but not on pypi yet....

**Pull request merged**
