### PR TITLE
Add support for split JEC uncertainties sources

### PR DESCRIPTION
**Pull request by mverzett**
There are no unit tests added, please let me know if/where to put them.

### CODE REVIEW

**Comment by nsmith-** [comment]
Will extending https://github.com/CoffeaTeam/fnal-column-analysis-tools/blob/master/tests/test_lookup_tools.py#L81 work for this case?  If not, feel free to add more tests.

**Comment by lgray** [comment]
Was about to ask the same thing. Please add a test to make sure all cases work.

**Comment by mverzett** [comment]
OK, done. Thanks for pointing me the location

**Comment by nsmith-** [comment]
So you'll probably want to pull master into your branch to deal with #69 but the python 2.7 failure might be legitimate.  @lgray its something in the numpy text converter, maybe you are familiar

**Comment by lgray** [comment]
@mverzett I'll take a look today.

**Comment by mverzett** [comment]
@lgray for the record: I tried running locally in a python 2.7 env and it did not crash. I create some temporary files to split the sources, could they be the cause of the crash?

**Comment by nsmith-** [comment]
@mverzett can you try pulling master in, and pushing to the branch?  Maybe the test fail is temporary (other than the unrelated numba thing)

**Comment by lgray** [comment]
@mverzett Hey, so it fails for me as well in python3 on my mac.

Investigating.

**Comment by lgray** [comment]
@mverzett Indeed, this isn't something that's compatible across systems.

I would suggest you instead chop up the files into strings in memory and then parse those using the StringIO file-like wrapper for strings.

**Comment by lgray** [comment]
@mverzett Any movement here?

**Comment by lgray** [comment]
please rebase this to master!

**Comment by mverzett** [comment]
Hi, sorry for the long silence, got stuck in other projects/workshops. I’ll try to complete it by the end of the week.

**Comment by lgray** [comment]
@mverzett No worries, just keeping the PR warm.

**Comment by lgray** [comment]
@mverzett the pytest stuff passed but you've got a bunch of flake8 compliance issues.
Just do `python setup.py flake8` to get your own copy of the list.

**Comment by lgray** [comment]
@nsmith- Can you have a quick look at this one, any comments?

**Comment by nsmith-** [comment]
I don't have any issue

**Pull request merged**
