### PR TITLE
work queue: implement retries executor argument

### PR DESCRIPTION
**Pull request by btovar**
On failure, a task is now retried (a default of 2 times) with the work queue executor.

### CODE REVIEW

**Comment by lgray** [comment]
pyarrow5 is causing some problems.
I'll try to look into it today.

**Comment by btovar** [comment]
thanks @lgray!

**Comment by lgray** [comment]
@btovar please fix flake8/black complaints

**Comment by lgray** [comment]
And now conflicts with the master branch. Nothing too big though. Ping me when you've fixed things up!

**Comment by btovar** [comment]
@lgray argh, sorry about the conflict errors, it seems that I pushed extra commits to this branch.

**Comment by btovar** [comment]
@lgray thanks!

**Pull request merged**
