### PR TITLE
test and fix for 2D JER SF lookup

### PR DESCRIPTION
**Pull request by jpata**
Added a unit test for 2D lookup of JER SF, needed for the latest Autumn18_V7_MC_SF tag, which fails. An issue will follow shortly :)

### CODE REVIEW

**Comment by jpata** [comment]
Here's the related issue: https://github.com/CoffeaTeam/coffea/issues/191

**Comment by jpata** [comment]
Seems like https://github.com/CoffeaTeam/coffea/pull/190/commits/72ca7a125512adf031d5de58493a38a3246fc8d5 fixed it: the output SF arrays are already jagged with the correct structure, so the flattening can be done afterwards, treating 1D as a special case of n-D.

**Comment by lgray** [comment]
@jpata Can you make that automatically happen (if it's not already)?

**Comment by jpata** [comment]
As far as I can tell it is already automatic, in the sense that both the original 1D test and the new 2D test pass and there is no `if/else` required. In the 1D case, the `_parms` ends up being a jagged array with every element being count-1. I checked a few elements by hand and it seems to retrieve the correct values.

**Comment by lgray** [comment]
Indeed, everything else looks good.

I'll go ahead and merge.

**Comment by lgray** [comment]
Ah, right, speed.

Can you do a quick regression test on this for execution speed?

**Pull request merged**
