### PR TITLE
Pronunciation

### PR DESCRIPTION
**Pull request by andrzejnovak**
This the right one? 😅

### CODE REVIEW

**Comment by lgray** [comment]
Yep, it's the right one :-)

Can you put the pronunciation centered below the name instead of to the right? Otherwise it could confuse people.

Also you can use [skip ci] at the front of the commit message when you're only editing text. :-)

**Comment by andrzejnovak** [comment]
hmm @lgray can that be done in markdown?

**Comment by andrzejnovak** [comment]
hmm @lgray can that be done in markdown?

**Comment by lgray** [comment]
I have no idea!

**Comment by andrzejnovak** [comment]
Ok, I give up RST, is retarded.

**Pull request closed without merging**
