### PR TITLE
Remove python2 tests and warn if in python2

### PR DESCRIPTION
**Pull request by lgray**
To merge on 1 Jan 2020.

### CODE REVIEW

**Comment by andrzejnovak** [comment]
is uproot dropping py3?

**Comment by lgray** [comment]
@jpivarski ?

**Comment by jpivarski** [comment]
I'll be supporting Python 2.7 as long as it's easily possible (i.e. we can use conda to install packages). There's a Scikit-HEP declaration that we don't have to, but I will. That doesn't mean you have to.

**Comment by nsmith-** [comment]
I think this might be a bit too restrictive.  We have a large code base that is py2 compatible at the moment.  Maybe we allow it but no longer test.  If a user tries to run it, one could e.g. emit a warning and if something breaks perhaps they will make a PR with the necessary changes.

**Comment by lgray** [comment]
Sure, that's reasonable. Wasn't sure how ... provocative... we wanted to be.

**Pull request merged**
