### PR TITLE
feat: also pass `uproot_options` to `uproot.dask` in `from_root()`

### PR DESCRIPTION
**Pull request by ikrommyd**
I also had to comply to the other changes in nanoevents in `local_executors_to_dask` which were changing the `chunks_per_file` to `None` and also adding this `elif chunks_per_file is None`.

### CODE REVIEW

**Comment by ikrommyd** [comment]
@lgray apparently changing the default `chunks_per_file` to `None` causes the local_executor tests to fail. I checked locally

**Comment by lgray** [comment]
Don't worry about those they're going away. Would remove that fix from this patch. Chunks_per_file=None should be in the PR with preprocess.

**Comment by ikrommyd** [comment]
alright, but I'm keeping the `elif chunks_per_file is None` since there is `uproot_options` passing there

**Comment by nikoladze** [comment]
i also wanted to suggest passing `uproot_options` to `uproot.dask` in dask mode - i'm currently experimenting with custom uproot sources that i could then pass as `file_handler` or `http_handler` arguments here

**Comment by lgray** [comment]
yeah! this is definitely going in - especially if we want fspec to work with root files correctly, many more options may need to be passed.

**Comment by lgray** [comment]
@iasonkrom please make sure these changes work well for you. Now I'm using uproot's mechanism for setting the default of the file chunking. Should work reasonably in all cases now.

**Comment by ikrommyd** [comment]
It should be fine like that. It's just that now `chunks_per_file=None` is no longer an option and it will run into `unsupported operand type(s) for *: 'int' and 'NoneType'` from uproot. So we are just complying to uproot's interface of requiring only `int` `steps_per_file` while `None` corresponds to just "leave the default option"

**Pull request merged**
