### PR TITLE
Serialization improvements in for hist.Bin

### PR DESCRIPTION
**Pull request by lgray**
Code used to make the benchmark:
image

Histogram definition (filled with HZZ events from `http://scikit-hep.org/uproot/examples/HZZ.root`):
image

Original bins implementation on ~40000 dense bins:
image

without saving the Intervals list, and building it lazily:
image

This has significant benefits for running at scale!
@nsmith-

### CODE REVIEW

**Review by nsmith- — APPROVED** [review]
I suppose a fast path for adding histograms is important in reduction stage, vs. re-assembling the full python objects.  A proper serialization format would sidestep it.

**Comment by lgray** [comment]
Yeah a proper serialization format would be welcome... 

The summing operation itself doesn't take much time - ~150us for 40k bin histogram, so take what we can get here I guess.

**Comment by nsmith-** [comment]
Proper serialization will come with boost-histogram. As for this case, it's a bit pathological to have 40000 bins in one axis. The complexity here is sum of nbins, not product, so really for most use it should be negligible.

**Comment by lgray** [comment]
Eh, as people go to higher dim histograms we'll run into this one way or another. *shrug*

**Pull request merged**
